name: CI

on: [push, pull_request]

jobs:
  packages:
    name: Client Packages
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
  build:
    name: Client Build
    runs-on: ubuntu-latest
    needs: [packages]
    env:
      CI: true
      NODE_ENV: production
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - run: npm run build
  lint:
    name: Client Lint
    runs-on: ubuntu-latest
    needs: [packages]
    env:
      CI: true
      NODE_ENV: production
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - run: npm run lint
