name: release

on:
  push:
    tags:
      - v*.*.*
    branches-ignore:
      - '**'

env:
  IMAGE_NAME: trap-collection-admin

jobs:
  make-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      # TODO: npm run build
      - run: npx vite build
      - name: Archive artifact
        run: tar -zcvf ./dist.tar.gz ./dist
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist.tar.gz
  build-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo IMAGE_TAG=$(echo ${GITHUB_REF:11}) >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: traptitech
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/traptitech/${{ env.IMAGE_NAME }}:latest
            ghcr.io/traptitech/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
